# Draw a clock
import turtle
# Move the pen
turtle.penup()
turtle.goto(-15, -150)
turtle.pendown()
# Drawing a circle
turtle.circle(180)
# Number in the clock
turtle.penup()
turtle.goto(-25, 160)
turtle.pendown()
turtle.write("12", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(55, 130)
turtle.pendown()
turtle.write("1", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(105, 90)
turtle.pendown()
turtle.write("2", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(125, 30)
turtle.pendown()
turtle.write("3", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(110, -30)
turtle.pendown()
turtle.write("4", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(55, -75)
turtle.pendown()
turtle.write("5", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(-20, -110)
turtle.pendown()
turtle.write("6", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(-100, -75)
turtle.pendown()
turtle.write("7", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(-140, -25)
turtle.pendown()
turtle.write("8", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(-155, 30)
turtle.pendown()
turtle.write("9", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(-145, 90)
turtle.pendown()
turtle.write("10", font=("Arial", 24, "normal"))
turtle.penup()
turtle.goto(-100, 130)
turtle.pendown()
turtle.write("11", font=("Arial", 24, "normal"))
# Show 9:15
turtle.penup()
turtle.goto(-15, 40)
turtle.pendown()
turtle.forward(80)
turtle.penup()
turtle.goto(-15, 40)
turtle.pendown()
turtle.left(90)
turtle.forward(100)
turtle.hideturtle()

turtle.done()
